# Basic Information 
title: Qifan Fu
position: Ph.D. student
affiliation: Osaka University
affiliation_link: https://www.econ.osaka-u.ac.jp/en/
affiliation_logo: ./assets/img/university-logo-small-horizontal-blue-156eae9527.svg
email: u670245b (at) ecs.osaka-u.ac.jp

# Search Engine Optimization (SEO)
keywords: fuqifan, fqf, qifanfu
canonical: https://www.osaka-u.ac.jp/ja
description: fuqifan's homepage.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: text #text/icon
cv_link: ./assets/img/Comingsoon.pdf
linkedin: https://www.linkedin.com/in/fu-qifan-b41361222/


# Images 
avatar: ./assets/img/IMG_1149.HEIC
favicon: ./assets/img/RUNOOB-SVG-IMAGE-2.png
favicon_dark: ./assets/img/RUNOOB-SVG-IMAGE-2.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
